[supervisord]
nodaemon=true
user=root
pidfile=/tmp/supervisord.pid
logfile=/dev/null
logfile_maxbytes=0

[program:backend]
command=/opt/java/openjdk/bin/java -XX:MaxRAMPercentage=70 -jar /app/app.jar
directory=/app
priority=10
autostart=true
autorestart=true
startsecs=8
stopasgroup=true
killasgroup=true
stopsignal=TERM
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
priority=20
autostart=true
autorestart=true
startsecs=2
stopasgroup=true
killasgroup=true
stopsignal=QUIT
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
